
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package midik.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 30;
  public static final int CHAR = 11;
  public static final int ENTERO = 45;
  public static final int CASE = 52;
  public static final int DIFERENTE = 38;
  public static final int DOUBLE = 10;
  public static final int DOS_PUNTOS = 54;
  public static final int INT = 7;
  public static final int LLAVE_C = 25;
  public static final int FOR = 14;
  public static final int LLAVE_A = 24;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int PRIVATED = 4;
  public static final int IGUAL = 32;
  public static final int CARACTER = 50;
  public static final int OR = 40;
  public static final int CLASS = 6;
  public static final int INCREMENTO = 42;
  public static final int IF = 12;
  public static final int ID = 44;
  public static final int DECIMAL = 46;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int RETURN = 20;
  public static final int TRUE = 48;
  public static final int DECREMENTO = 43;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int CADENA = 47;
  public static final int MENOS = 29;
  public static final int NULL = 51;
  public static final int MAYOR_QUE = 36;
  public static final int BREAK = 19;
  public static final int VOID = 55;
  public static final int ASIGNACION = 35;
  public static final int SWITCH = 17;
  public static final int IMPORT = 2;
  public static final int ELSE = 13;
  public static final int PROTECTED = 5;
  public static final int PUNTO = 22;
  public static final int PARENTESIS_C = 27;
  public static final int FINAL = 18;
  public static final int WHILE = 15;
  public static final int PARENTESIS_A = 26;
  public static final int DEFAULT = 53;
  public static final int MAYOR_IGUAL = 33;
  public static final int PUBLIC = 3;
  public static final int P_COMA = 21;
  public static final int STRING = 9;
  public static final int MENOR_QUE = 37;
  public static final int MENOR_IGUAL = 34;
  public static final int FALSE = 49;
  public static final int DIVISION = 31;
  public static final int DO = 16;
  public static final int MAS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPORT",
  "PUBLIC",
  "PRIVATED",
  "PROTECTED",
  "CLASS",
  "INT",
  "BOOLEAN",
  "STRING",
  "DOUBLE",
  "CHAR",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "FINAL",
  "BREAK",
  "RETURN",
  "P_COMA",
  "PUNTO",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "IGUAL",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "ASIGNACION",
  "MAYOR_QUE",
  "MENOR_QUE",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "TRUE",
  "FALSE",
  "CARACTER",
  "NULL",
  "CASE",
  "DEFAULT",
  "DOS_PUNTOS",
  "VOID"
  };
}

